---
- name: Install software using brew
  homebrew:
    name:
      - autojump
      - aws-vault
      - coreutils
      - exiftool
      - gpg
      - htop
      - ipcalc
      - jq
      - kubectl
      - neovim
      - pwgen
      - pv
      - reattach-to-user-namespace
      - ripgrep
      - tmux
      - vim
      - wget
      - yamllint
      - zsh
    update_homebrew: true

- name: Install software using brew cask
  homebrew_cask:
    name:
      - firefox
      - iterm2
      - postman
      - slack
      - sublime-text
      - visual-studio-code

- name: Get architecture of system
  shell: uname -m
  args:
    executable: /bin/bash
  register: get_system_arch

- name: Install software for x86_64 systems only
  homebrew_cask:
    name:
      - virtualbox
      - virtualbox-extension-pack
  when: get_system_arch.stdout == "x86_64"
