---
- name: Install software using brew
  community.general.homebrew:
    name:
      - autojump
      - aws-vault
      - coreutils
      - exiftool
      - gpg
      - htop
      - ipcalc
      - jq
      - kubectl
      - neovim
      - pwgen
      - pv
      - reattach-to-user-namespace
      - ripgrep
      - tmux
      - vault
      - vim
      - wget
      - yamllint
      - zsh
    update_homebrew: true

- name: Tap homebrew/cask-versions
  community.general.homebrew_tap:
    name: homebrew/cask-versions

- name: Install software using brew cask
  community.general.homebrew_cask:
    name:
      - firefox
      - iterm2
      - postman
      - slack
      - sublime-text
      - visual-studio-code
  become: yes

- name: Get architecture of system
  ansible.builtin.shell: uname -m
  args:
    executable: /bin/bash
  register: get_system_arch
  changed_when: False

- name: Install software for x86_64 systems only
  community.general.homebrew_cask:
    name:
      - virtualbox
      - virtualbox-extension-pack
  when: get_system_arch.stdout == "x86_64"
