---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.3.0
    hooks:
      - id: ansible-lint
  - repo: git@github.com:jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shfmt
        args: ["-i", "2", "-sr"]
        exclude: |
          (?x)^(
            roles/system/files/install-nvm-0.35.0.sh
          )$
