#!/bin/bash

set -e

retcode=0

sudo apt-get install -y \
  gcc \
  git \
  libbz2-dev \
  libffi-dev \
  libreadline-dev \
  libsqlite3-dev \
  libssl-dev \
  make \
  python-dev \
  zlib1g-dev

if ! command -v pyenv >/dev/null 2>&1; then
  git clone git://github.com/pyenv/pyenv ~/.pyenv
  echo 'export PYENV_ROOT="${HOME}/.pyenv"' >> ~/.bashrc
  echo 'export PATH="${PYENV_ROOT}/bin:${PATH}"' >> ~/.bashrc
  echo -e 'if command -v pyenv >/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc

  export PYENV_ROOT="${HOME}"/.pyenv
  export PATH="${PYENV_ROOT}/bin:${PATH}"
  eval "$(pyenv init -)"

  pyenv_venv_dir="$(pyenv root)/plugins/pyenv-virtualenv"
  if ! test -d "${pyenv_venv_dir}"; then
    git clone git://github.com/pyenv/pyenv-virtualenv "${pyenv_venv_dir}"
    echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
    eval "$(pyenv virtualenv-init -)"
  fi
fi

python_version=3.8.0
set +e
grep -q "${python_version}" <<< "$(pyenv versions)"
retcode=${?}
set -e
if [ "${retcode}" -ne 0 ]; then
  pyenv install "${python_version}"
fi

set +e
grep -q 'provision-ubuntu' <<< "$(pyenv versions)"
retcode=${?}
set -e
if [ "${retcode}" -ne 0 ]; then
  pyenv virtualenv "${python_version}" provision-ubuntu
fi

eval "$(pyenv init -)"
pyenv activate provision-ubuntu

pip install -r requirements.txt
ansible-playbook -v -K -i inventory "$@" localhost.yml
pyenv deactivate

# Set global python version
pyenv global "${python_version}"

# Install neovim-remote
if [ 0 -eq "$(pip3 list --user | grep neovim-remote | wc -l)" ]; then
  pip3 install --user neovim-remote
fi

printf "\n\nPlease run the following commands to complete the setup:\n\n"
printf "    exec \"\${SHELL}\"\n"
printf "    chsh --shell /bin/zsh yh\n"
printf "\n\nAfter setting your iptables rules, run:\n\n"
printf "    sudo dpkg-reconfigure iptables-persistent\n\n"
