#!/bin/bash

set -x
set -e

early_abort=false
retcode=0

if ! command -v pyenv >/dev/null 2>&1; then
  git clone git://github.com/pyenv/pyenv ~/.pyenv
  echo 'export PYENV_ROOT="${HOME}/.pyenv"' >> ~/.bashrc
  echo 'export PATH="${PYENV_ROOT}/bin:${PATH}"' >> ~/.bashrc
  echo -e 'if command -v pyenv >/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc
  early_abort=true

  pyenv_venv_dir="$(pyenv root)/plugins/pyenv-virtualenv"
  if ! test -d "${pyenv_venv_dir}"; then
    git clone git://github.com/pyenv/pyenv-virtualenv "${pyenv_venv_dir}"
    echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
  fi
fi

if ! dpkg -s python-dev
then
  sudo apt-get -y install python-dev
fi

if [ "${early_abort}" == "true" ]; then
  printf "Please run 'exec \${SHELL}', then run this program again. Exiting.\n"
  exit 0
fi

sudo apt-get install -y \
  gcc \
  libbz2-dev \
  libffi-dev \
  libreadline-dev \
  libsqlite3-dev \
  libssl-dev \
  make \
  zlib1g-dev

set +e
grep -q '3.7.4' <<< "$(pyenv versions)"
retcode=${?}
set -e
if [ "${retcode}" -ne 0 ]; then
  pyenv install 3.7.4
fi

pip install -r requirements.txt
ansible-playbook -v -K -i inventory localhost.yml
