---
- name: check {{ apt_sources_list }} to see if sg mirror is used
  ansible.builtin.shell: "set -o pipefail && cat {{ apt_sources_list }} | perl -ne 'print if /^(deb|deb-src) http:\\/\\/sg.archive.ubuntu.com/' | wc -l"
  args:
    executable: /bin/bash
  register: nr_lines_with_sg_mirror_in_apt_sources
  changed_when: False

- name: replace {{ apt_sg_mirror }} mirrors with {{ apt_osuosl_mirror }} mirror
  ansible.builtin.shell: perl -pi -e 's#^(deb|deb-src) {{ apt_sg_mirror }}#\1 {{ apt_osuosl_mirror }}#' /etc/apt/sources.list
  args:
    executable: /bin/bash
  when: nr_lines_with_sg_mirror_in_apt_sources.stdout | int > 0  # noqa risky-shell-pipe

- name: Get output of lsb_release -cs
  ansible.builtin.shell: lsb_release -cs
  register: lsb_release_cs
  changed_when: False

- name: Add virtualbox key
  ansible.builtin.apt_key:
    file: "{{ ubuntu_packages_files_path }}/oracle_vbox_2016.asc"
    id: "B9F8D658297AF3EFC18D5CDFA2F683C52980AECF"
  register: add_vbox_apt_key
  become: yes

- name: Add virtualbox apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ lsb_release_cs.stdout }} contrib"
  register: add_vbox_apt_repo
  become: yes

- name: Add sublime text apt key
  ansible.builtin.apt_key:
    file: "{{ ubuntu_packages_files_path }}/sublimehq-pub.gpg"
    id: "1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A"
  register: add_subl_apt_key
  become: yes

- name: Add sublime text apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
  register: add_subl_apt_repo
  become: yes

- name: Add Google Cloud apt key (also for k8s)
  ansible.builtin.apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
  register: add_gcloud_apt_key
  become: yes

- name: Add docker apt key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
  register: add_docker_apt_key
  become: yes

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release_cs.stdout }} stable"
  register: add_docker_apt_repo
  become: yes

- name: Add Hashicorp apt key
  ansible.builtin.apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
  register: add_hashicorp_apt_key
  become: yes

- name: Add Hashicorp apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsb_release_cs.stdout }} main"
  register: add_hashicorp_apt_repo
  become: yes

# Refer to https://code.visualstudio.com/docs/setup/linux?msclkid=1ac46317bc6411ecb47fb8ff0f8c2151
- name: Add Microsoft packages apt key
  ansible.builtin.apt_key:
    file: "{{ ubuntu_packages_files_path }}/packages.microsoft.gpg"
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
  register: add_ms_pkg_apt_key
  become: yes

- name: Add Microsoft apt repo
  ansible.builtin.lineinfile:
    line: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    path: /etc/apt/sources.list.d/vscode.list
    owner: root
    group: root
    create: yes
    mode: 0644
  register: add_ms_apt_repo
  become: yes

- name: Add git-core ppa
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
  register: add_gitcore_ppa
  become: yes

- name: Check if we need to perform apt-get update (if last update was > 1 day ago OR if we just replaced apt sg mirror)
  ansible.builtin.shell: |
    set -euo pipefail
    last_update="$(stat /var/cache/apt/pkgcache.bin | grep -Po '^Access: \K\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}')"
    last_update_ts="$(date +%s -d "${last_update}")"
    ts_now="$(date +%s)"
    if [ "$(( ${ts_now} - ${last_update_ts} ))" -gt 86400 ]; then
      echo "please update"
    else
      echo "up to date"
    fi
  args:
    executable: /bin/bash
  register: ag_update
  become: yes
  changed_when: False

- name: apt-get update
  ansible.builtin.apt:
    update_cache: yes
  when: ag_update.stdout == "please update" or add_vbox_apt_key.changed or add_vbox_apt_repo.changed or add_subl_apt_key.changed or add_subl_apt_repo.changed or add_gcloud_apt_key.changed or add_hashicorp_apt_key.changed or add_hashicorp_apt_repo.changed or add_docker_apt_key.changed or add_docker_apt_repo.changed or add_ms_pkg_apt_key.changed or add_ms_apt_repo.changed or add_gitcore_ppa.changed  # noqa no-handler
  become: yes

- name: List the packages to install
  ansible.builtin.set_fact:
    ubuntu_packages:
      - apt-transport-https
      - autojump
      - ca-certificates
      - chromium-browser
      - code
      - containerd.io
      - curl
      - docker-ce
      - docker-ce-cli
      # get metadata of image files
      - exiftool
      - expat
      - expect
      - ffmpeg
      - fd-find
      - firefox
      - g++
      - gcc
      - gdb
      - gimp
      - git
      - gnupg-agent
      - htop
      - imagemagick
      - iptables-persistent
      - ipcalc
      - jq
      - keepass2
      - libbz2-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
      - libgmp-dev
      - liblzma-dev
      - libmysqlclient-dev
      - libncurses5-dev
      - libpcre3
      - libpcre3-dev
      - libreoffice-calc
      - libreoffice-writer
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - lzma-dev
      - make
      - mc    # midnight commander
      - net-tools
      - octave
      - openjdk-8-jdk
      - protobuf-compiler
      - pwgen
      - pv
      - r-base
      - remmina
      - ripgrep
      - screen
      - scrot
      - sqlite3
      - sublime-text
      - tcl8.6
      - tcl8.6-dev
      - tk8.6
      - tk8.6-dev
      - tmux
      - unzip
      - vagrant
      - vim
      - virtualbox-6.1
      - vlc
      - xchm
      - xclip
      - xsel
      - yamllint
      - zlib1g-dev
      - zsh

- name: install some packages
  ansible.builtin.apt:
    name: "{{ ubuntu_packages }}"
    state: present
  become: yes

# From https://github.com/microsoft/vscode-postgresql/issues/77#issuecomment-701495023
- name: Check if libffi6 is installed
  ansible.builtin.shell: dpkg -L libffi6
  register: check_if_libffi6_installed
  ignore_errors: true
  changed_when: false

- name: Download libffi6
  ansible.builtin.get_url:
    url: "{{ libffi6.url }}"
    dest: "{{ libffi6.download_dest }}"
    checksum: "sha256:{{ libffi6.sha256sum }}"
    mode: 0644
  when: check_if_libffi6_installed.rc != 0

- name: Install libffi6
  ansible.builtin.apt:
    deb: "{{ libffi6.download_dest }}"
  become: yes

- name: Check if bat is installed
  ansible.builtin.shell: dpkg -L bat-musl
  register: check_if_bat_installed
  ignore_errors: true
  changed_when: false

- name: Download bat debian package
  ansible.builtin.get_url:
    url: "{{ bat.url }}"
    dest: "{{ bat.download_dest }}"
    checksum: "sha256:{{ bat.sha256sum }}"
    mode: 0644
  when: check_if_bat_installed.rc != 0

- name: Install bat
  ansible.builtin.apt:
    deb: "{{ bat.download_dest }}"
  become: yes

- name: Check if neovim is installed
  ansible.builtin.shell: command -v nvim >/dev/null 2>&1
  register: check_if_neovim_installed
  ignore_errors: true
  changed_when: false

- name: Download nvim.appimage
  ansible.builtin.get_url:
    url: "{{ nvim.url }}"
    dest: "{{ nvim.download_dest }}"
    checksum: "sha256:{{ nvim.sha256sum }}"
    mode: 0755
  when: check_if_neovim_installed.rc != 0

- name: Copy nvim.appimage to /usr/local/bin
  delegate_to: localhost
  ansible.builtin.copy:
    src: "{{ nvim.download_dest }}"
    dest: /usr/local/bin/nvim
    mode: 0755
    owner: root
  become: yes

- name: Check if balena etcher is installed
  ansible.builtin.shell: dpkg -L balena-etcher
  register: check_if_balena_etcher_installed
  ignore_errors: true
  changed_when: false

- name: Download balena etcher debian package
  ansible.builtin.get_url:
    url: "{{ balena_etcher.url }}"
    dest: "{{ balena_etcher.download_dest }}"
    checksum: "sha256:{{ balena_etcher.sha256sum }}"
    mode: 0644
  when: check_if_balena_etcher_installed.rc != 0

- name: Install balena etcher
  ansible.builtin.apt:
    deb: "{{ balena_etcher.download_dest }}"
  become: yes
