---
- name: clone oh my zsh repository
  ansible.builtin.git:
    repo: git@github.com:robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    accept_newhostkey: yes
    update: no

- name: clone dotfiles repository
  ansible.builtin.git:
    repo: git@github.com:yanhan/dotfiles.git
    dest: "{{ dotfiles_repo_path }}"
    accept_newhostkey: yes
    update: no
  notify: setup dotfiles repository
  tags:
    - dotfiles

- name: Ensure ${HOME}/.vim/autoload exists
  ansible.builtin.file:
    path: "{{ home_path }}/.vim/autoload"
    state: directory
    mode: 0750
