---
- name: Clone fzf repo
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    accept_newhostkey: true
    depth: 1
    dest: "{{ home_path }}/.fzf"
    update: yes
  tags:
    - fzf

- name: Run fzf install script
  ansible.builtin.shell: "{{ home_path }}/.fzf/install"
  args:
    executable: /bin/bash
  tags:
    - fzf
