---
- name: clone oh my zsh repository
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    accept_newhostkey: yes
    update: no
  tags:
    - dotfiles

- name: clone zsh-nvm repository for lazy loading nvm
  ansible.builtin.git:
    repo: https://github.com/lukechilds/zsh-nvm.git
    dest: ~/.zsh-nvm
    accept_newhostkey: yes
    update: no
  tags:
    - dotfiles

- name: clone packer.nvim repo to manage neovim plugins
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ home_path }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    accept_newhostkey: yes
    update: no
  tags:
    - dotfiles

- name: clone dotfiles repository
  ansible.builtin.git:
    repo: https://github.com/yanhan/dotfiles.git
    dest: "{{ dotfiles_repo_path }}"
    accept_newhostkey: yes
    update: no
  notify: setup dotfiles repository
  tags:
    - dotfiles

- name: Ensure tmux plugins dir exists
  ansible.builtin.file:
    path: "{{ home_path }}/.tmux/plugins"
    state: directory
    mode: 0750
  tags:
    - dotfiles

- name: clone tmux plugins manager repository
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ home_path }}/.tmux/plugins/tpm"
    accept_newhostkey: yes
    update: no
  tags:
    - dotfiles

- name: Compare init.vim contents
  ansible.builtin.shell: |
    diff -q {{ home_path }}/dotfiles/templates/init.vim {{ home_path }}/.config/nvim/init.vim
  args:
    executable: /bin/bash
  register: init_vim_diff
  changed_when: false
  ignore_errors: true
  tags:
    - dotfiles

- name: Notify setup dotfiles handler if needed
  ansible.builtin.debug:
    var: init_vim_diff
  notify: setup dotfiles repository
  changed_when: true
  when: init_vim_diff.rc != 0
  tags:
    - dotfiles
