---
- name: Set fact for asdf managed plugins and tools
  ansible.builtin.set_fact:
    asdf_plugins:
      - name: argocd
        repo: https://github.com/beardix/asdf-argocd.git
        versions:
          - 3.1.8
        global: 3.1.8
      - name: doctl
        repo: https://github.com/maristgeek/asdf-doctl.git
        versions:
          - 1.145.0
        global: 1.145.0
      - name: golang
        repo: https://github.com/kennyp/asdf-golang.git
        versions:
          - 1.25.2
        global: 1.25.2
      - name: gomplate
        repo: https://github.com/sneakybeaky/asdf-gomplate.git
        versions:
          - v4.3.3
        global: v4.3.3
      - name: helm
        repo: https://github.com/Antiarchitect/asdf-helm.git
        versions:
          - 3.19.0
        global: 3.19.0
      - name: jb
        repo: https://github.com/beardix/asdf-jb.git
        versions:
          - 0.5.1
        global: 0.5.1
      - name: kind
        repo: https://github.com/johnlayton/asdf-kind.git
        versions:
          - 0.30.0
        global: 0.30.0
      - name: kubectl
        repo: https://github.com/Banno/asdf-kubectl.git
        versions:
          - 1.23.10
          - 1.24.12
          - 1.32.9
        global: 1.32.9
      - name: lua
        repo: https://github.com/Stratus3D/asdf-lua.git
        versions:
          - 5.4.7
        global: 5.4.7
      - name: pre-commit
        repo: https://github.com/jonathanmorley/asdf-pre-commit.git
        versions:
          - 4.3.0
        global: 4.3.0
      - name: shellcheck
        repo: https://github.com/luizm/asdf-shellcheck.git
        versions:
          - 0.11.0
        global: 0.11.0
      - name: shfmt
        repo: https://github.com/luizm/asdf-shfmt.git
        versions:
          - 3.12.0
        global: 3.12.0
      - name: tanka
        repo: https://github.com/trotttrotttrott/asdf-tanka.git
        versions:
          - 0.35.0
        global: 0.35.0
  tags:
    - asdf

- name: Get architecture of system
  ansible.builtin.shell: uname -m
  args:
    executable: /bin/bash
  register: get_system_arch_for_asdf
  changed_when: False
  tags:
    - asdf

- name: Check if asdf is installed
  ansible.builtin.shell: command -v asdf >/dev/null 2>&1
  register: check_if_asdf_installed
  ignore_errors: true
  changed_when: false
  tags:
    - asdf

- name: Download asdf for x86_64
  ansible.builtin.get_url:
    url: "{{ asdf_x86_64.url }}"
    dest: "{{ asdf_x86_64.download_dest }}"
    checksum: "sha256:{{ asdf_x86_64.sha256sum }}"
    mode: 0644
  when: check_if_asdf_installed.rc != 0 and get_system_arch_for_asdf.stdout == "x86_64"
  tags:
    - asdf

- name: Untar asdf and copy to /usr/local/bin for x86_64
  delegate_to: localhost
  ansible.builtin.unarchive:
    src: "{{ asdf_x86_64.download_dest }}"
    dest: /usr/local/bin
    mode: 0755
    owner: root
  become: yes
  when: check_if_asdf_installed.rc != 0 and get_system_arch_for_asdf.stdout == "x86_64"
  tags:
    - asdf

- name: Add asdf plugins
  ansible.builtin.shell: |
    if [[ "$(grep -c  "{{ item.name }}" <<< "$(asdf plugin list)")" -eq 0 ]]; then
      asdf plugin add "{{ item.name }}" "{{ item.repo }}"
    fi
  args:
    executable: /bin/bash
  loop: "{{ asdf_plugins | flatten(levels=1) }}"
  changed_when: False
  tags:
    - asdf

- name: Install packages
  ansible.builtin.shell: |
    if [[ "$(grep -c "{{ item.1 }}" <<< "$(asdf list "{{ item.0.name }}")")" -eq 0 ]]; then
      asdf install "{{ item.0.name }}" "{{ item.1 }}"
    fi
  args:
    executable: /bin/bash
  loop: "{{ asdf_plugins | subelements('versions') }}"
  changed_when: False
  tags:
    - asdf

- name: Set global versions of packages
  ansible.builtin.shell: |
    asdf set -u "{{ item.name }}" "{{ item.global }}"
  args:
    executable: /bin/bash
  loop: "{{ asdf_plugins | flatten(levels=1) }}"
  changed_when: False
  tags:
    - asdf
