---
- name: Check if minikube is installed
  shell: command -v minikube >/dev/null 2>&1
  ignore_errors: yes
  changed_when: False
  register: minikube_installed

- name: Install minikube
  apt:
    deb: "https://github.com/kubernetes/minikube/releases/download/v1.24.0/minikube_1.24.0-0_amd64.deb"
  become: yes
  when: minikube_installed.rc != 0
