---
- name: Install zsh-git-prompt
  include_tasks: install-zsh-git-prompt.yml

- name: Install fzf
  include_tasks: install-fzf.yml
  tags:
    - fzf

- include_tasks: install-dotfiles.yml

- name: Install asdf
  include_tasks: install-asdf.yml
  tags:
    - asdf

- name: Install ops tools
  include_tasks: install-ops-tools.yml
  tags:
    - ops

- name: Install nvm
  include_tasks: nvm.yml

- name: Install global npm packages
  include_tasks: npm-packages.yml
