---
- name: Set fact to store global npm packages
  ansible.builtin.set_fact:
    global_npm_packages:
      - jsonlint

- name: Install global npm packages
  community.general.npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ global_npm_packages }}"
