---
- name: Check if nvm is installed
  ansible.builtin.shell: "NVM_DIR=\"{{ nvm_dir }}\" && source \"${NVM_DIR}\"/nvm.sh && command -v nvm >/dev/null 2>&1"
  args:
    executable: /bin/bash
  register: check_nvm_installed
  ignore_errors: true
  changed_when: false
  tags:
    - nvm
    - upgrade_nvm

- name: Ensure $HOME/.nvm directory exists
  ansible.builtin.file:
    path: "{{ nvm_dir }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0700
  tags:
    - nvm
    - upgrade_nvm

- name: Install nvm
  ansible.builtin.shell: "{{ nvm_install_script_path }}"
  when: check_nvm_installed.rc != 0
  tags:
    - nvm

- name: Install nodejs using nvm
  ansible.builtin.shell: |
    NVM_DIR="{{ nvm_dir }}" && source "${NVM_DIR}"/nvm.sh && nvm install {{ nodejs_version }}
  args:
    executable: /bin/bash
  changed_when: False
  tags:
    - nvm

- name: Upgrade nvm
  ansible.builtin.shell: "{{ nvm_install_script_path }}"
  changed_when: False
  tags:
    - never
    - upgrade_nvm

- name: Install nodejs using nvm when upgrading nvm
  ansible.builtin.shell: |
    NVM_DIR="{{ nvm_dir }}" && source "${NVM_DIR}"/nvm.sh && nvm install {{ nodejs_version }}
  args:
    executable: /bin/bash
  changed_when: False
  tags:
    - never
    - upgrade_nvm

- name: Set default nodejs version
  ansible.builtin.shell: |
    NVM_DIR="{{ nvm_dir }}" && source "${NVM_DIR}"/nvm.sh && nvm alias default {{ nodejs_version }}
  args:
    executable: /bin/bash
  changed_when: False
  tags:
    - nvm
    - upgrade_nvm
