- name: Check if nvm is installed
  shell: "NVM_DIR=\"{{ ansible_env.HOME }}\"/.nvm source \"${NVM_DIR}\"/nvm.sh && command -v nvm >/dev/null 2>&1"
  args:
    executable: /bin/bash
  register: check_nvm_installed
  ignore_errors: true
  changed_when: false

- name: Ensure $HOME/.nvm directory exists
  file:
    path: "{{ ansible_env.HOME }}/.nvm"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0700

- name: Install nvm
  shell: "{{ nvm_install_script_path }}"
  when: check_nvm_installed.rc != 0

- name: Install nodejs 16.14.2 using nvm
  shell: "NVM_DIR=\"{{ ansible_env.HOME }}\"/.nvm source \"${NVM_DIR}\"/nvm.sh &&  nvm install 16.14.2"
  args:
    executable: /bin/bash
