apt_sources_list: /etc/apt/sources.list
apt_sg_mirror: http://sg.archive.ubuntu.com
apt_osuosl_mirror: http://ubuntu.osuosl.org

home_path: /home/yh
code_dir_path: "{{ home_path }}/code"
repo_files_path: "{{ code_dir_path }}/provision-ubuntu-ansible/roles/system/files"
tmp_downloads_path: "{{ repo_files_path }}/tmp_downloads"
home_bin_path: "{{ home_path }}/bin"

dotfiles_repo_path: "{{home_path}}/dotfiles"
vundle_repo_path: "{{home_path}}/.vim/bundle/Vundle.vim"
update_etc_environment_path_path: "{{ repo_files_path }}/update-etc-environment-path"
fonts_folder: "{{ repo_files_path}}/fonts/"
golang_binary_targz_fullpath: "{{ repo_files_path }}/go1.17.7.linux-amd64.tar.gz"
golang_binary_targz_sha256sum: "02b111284bedbfa35a7e5b74a06082d18632eff824fd144312f6063943d49259"
golang_binary_targz_url: "https://go.dev/dl/go1.17.7.linux-amd64.tar.gz"
home_fonts_path: "{{ home_path }}/.fonts/"
nvm_install_script_path: "{{ repo_files_path }}/install-nvm-0.35.0.sh"
ripgrep_deb:
  path: "{{ repo_files_path }}/ripgrep_11.0.2_amd64.deb"
  url: "https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb"
  sha256sum: "cecbe73abf3c672fde070c5c1d2ea303d97dae0af9afa0655028ae0d70dd11e8"
rsync_fonts_log_file_path: /tmp/pl-rsync-fonts-log-file
texlive_install_script_path: "{{ repo_files_path }}/install-texlive"
texlive_unix_installer_gz: install-tl-unx.tar.gz
texlive_unix_installer_gz_path: "{{ repo_files_path }}/{{ texlive_unix_installer_gz }}"
texlive_equivs_file_path: "{{ repo_files_path }}/debian-equivs-2018-ex.txt"
texlive_update_etc_environment_script_path: "{{ repo_files_path }}/texlive-update-etc-environment"
texlive_uninstall_script_path: "{{ repo_files_path }}/uninstall-texlive"

vagrant_2_2_6:
  url: "https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_linux_amd64.zip"
  sha256sum: "a08c7765baae1ee88b3bc0bace718087a84e2023d1f2ecc134aa735b89515a03"
  download_dest: "{{ tmp_downloads_path }}/vagrant_2.2.6_linux_amd64.zip"
  install_path: "{{ home_bin_path }}/vagrant"

libffi6:
  url: "https://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb"
  sha256sum: fa26945b0aadfc72ec623c68be9cc59235a7fe42e2388f7015fd131f4fb06dc9
  download_dest: "{{ tmp_downloads_path }}/libffi6_3.2.1-8_amd64.deb"
