---
- name: setup dotfiles repository
  ansible.builtin.shell: python setup_home_folder_dotfiles.py gitconfig tmux.conf vimrc zshrc
  args:
    chdir: "{{ dotfiles_repo_path }}"
  tags:
    - dotfiles
