---
- name: Install lock-screen script
  ansible.builtin.copy:
    src: lock-screen
    dest: /usr/local/bin/lock-screen
    owner: root
    group: root
    mode: "0755"
  become: yes

- name: Disable cups on system startup
  ansible.builtin.systemd:
    name: cups.service
    enabled: no
  become: yes
  ignore_errors: yes
